name: cds_portfolio
version: "1.0.0"
config-version: 2
profile: cds_portfolio

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets: ["target", "dbt_packages"]

models:
  cds_portfolio:
    +materialized: view
    education_attendance:
      staging:
        +schema: staging
        +materialized: view
      marts:
        +schema: marts
        +materialized: table
    healthcare_diagnosis:
      staging:
        +schema: staging
        +materialized: view
      marts:
        +schema: marts
        +materialized: table

seeds:
  cds_portfolio:
    +schema: reference
    icd10_reference:
      +column_types:
        icd10_code: text
        description: text
        category: text
        is_influenza: boolean
